export const SET_PROMOCODES = 'SET_PROMOCODES';
export const SET_USER_PROMOCODES = 'SET_USER_PROMOCODES';
export const SET_LOADING_START = 'SET_LOADING_START';
export const SET_SERVER = 'SET_SERVER';
export const SET_SUBFIELDS = 'SET_SUBFIELDS';